name = "wyasl"
version = "0.1.0"
defaultTargets = ["wyasl"]
license = "MIT"

[[lean_lib]]
name = "Wyasl"

[[lean_exe]]
name = "wyasl"
root = "Main"
needs = ["Wyasl"]

[[require]]
name = "Parser"
version = "git#main"
scope = "fgdorais"

[[require]]
name = "Cli"
version = "git#main"
scope = "leanprover"
